"""Curated Persian/Iranian first names for prospect discovery."""

IRANIAN_FIRST_NAMES = [
    "Abtin", "Afshin", "Anahita", "Anoushiravan", "Arash", "Ardeshir",
    "Ardalan", "Arman", "Armin", "Ashkan", "Azadeh", "Azar", "Babak",
    "Bahador", "Bahar", "Bahareh", "Bahman", "Bahram", "Behnam",
    "Behrang", "Behrooz", "Behzad", "Bijan", "Borna", "Dariush",
    "Daryoush", "Delara", "Elnaz", "Esfandiar", "Farah", "Farhad",
    "Fariba", "Farideh", "Farshad", "Farshid", "Farzad", "Farzaneh",
    "Faramarz", "Farnaz", "Fereydoun", "Firouz", "Forough", "Golnaz",
    "Golnar", "Haleh", "Hengameh", "Hirad", "Homa", "Homayoun",
    "Hooman", "Hormoz", "Houshang", "Iraj", "Jamshid", "Kambiz",
    "Kamran", "Katayoun", "Kaveh", "Kayvan", "Keyvan", "Khashayar",
    "Khosro", "Khosrow", "Kimia", "Kourosh", "Ladan", "Laleh",
    "Mahdis", "Mahnaz", "Mahsa", "Mahshid", "Mahtab", "Mahyar",
    "Mandana", "Manijeh", "Manouchehr", "Marjan", "Maziar", "Mehran",
    "Mehrdad", "Mehrnaz", "Mehrnoosh", "Mitra", "Mojgan", "Nahid",
    "Narges", "Nazanin", "Negar", "Negin", "Nika", "Niloofar",
    "Nima", "Nooshin", "Omid", "Parisa", "Parviz", "Payam", "Pedram",
    "Pejman", "Pouria", "Ramin", "Rambod", "Rostam", "Roshanak",
    "Roya", "Sahar", "Saman", "Sanaz", "Sasan", "Sepideh", "Sepehr",
    "Setareh", "Shabnam", "Shahin", "Shahram", "Shahrokh", "Shahrzad",
    "Shervin", "Shirin", "Shiva", "Shohreh", "Siavash", "Simin",
    "Sohrab", "Soheil", "Soroush", "Tahmineh", "Taraneh", "Touraj",
    "Yalda", "Yasaman", "Zhaleh",
    "Afarin", "Afsaneh", "Ahoo", "Aida", "Arezoo", "Arian", "Arya",
    "Asha", "Atieh", "Avesta", "Avin", "Baran", "Bardia", "Bita",
    "Dena", "Donya", "Elika", "Erfan", "Farangis", "Farbod", "Farrokh",
    "Farrokhzad", "Firoozeh", "Ghazal", "Ghazaleh", "Giti", "Gohar",
    "Gordafarid", "Hasti", "Helia", "Houman", "Ilia", "Kiana", "Kianoush",
    "Kiarash", "Kouroosh", "Liana", "Mahan", "Mahbod", "Mahdokht",
    "Mahla", "Mahrokh", "Mani", "Maral", "Mazdak", "Mehrab", "Mehrak",
    "Mehrangiz", "Mehregan", "Mehrshad", "Minoo", "Nahir", "Narmila",
    "Nastaran", "Navid", "Neda", "Nikta", "Niloufar", "Noushin", "Orkideh",
    "Pantea", "Parastoo", "Pardis", "Parham", "Pari", "Parnian", "Pegah",
    "Peyman", "Pirooz", "Pouya", "Raha", "Rana", "Rashin", "Roxana",
    "Rudabeh", "Sabalan", "Saba", "Sam", "Sarina", "Sarvenaz", "Shadan",
    "Shaghayegh", "Shahab", "Shahdad", "Shahriar", "Shapour", "Sheida",
    "Shideh", "Sogand", "Solmaz", "Soraya", "Sorour", "Sudabeh", "Tara",
    "Tina", "Vanda", "Vania", "Vida", "Yasna", "Yeganeh", "Ziba",
    "Zohreh",
]

IRANIAN_FIRST_NAMES += [
    "Abbas", "Abdolhossein", "Abdollah", "Abdolreza", "Abolfazl", "Adel",
    "Afsoon", "Afsoun", "Afsun", "Aghil", "Ahmad", "Akbar", "Akram",
    "Alborz", "Ali", "Alireza", "Amin", "Amineh", "Amir", "Arastoo",
    "Aref", "Arezou", "Arezu", "Aria", "Arzhang", "Asadollah", "Asal",
    "Asef", "Asghar", "Ashraf", "Atefeh", "Atousa", "Ava", "Ayda",
    "Ayoub", "Azad", "Aziz", "Azra", "Bagher", "Bakhtiar", "Baraz",
    "Behdad", "Behnaz", "Behnoosh", "Behnoush", "Behrouz", "Behruz",
    "Bismillah", "Burhanuddin", "Dana", "Danial", "Daniyal", "Dara",
    "Darya", "Daryush", "Davood", "Davoud", "Davud", "Delshad",
    "Ebrahim", "Ehsan", "Elaheh", "Elham", "Eskandar", "Eslam",
    "Esmaeel", "Esmaeil", "Esmail", "Esmat", "Fahimeh", "Farid",
    "Faridoon", "Fatemeh", "Fazel", "Fereshteh", "Fereydoon",
    "Fereydun", "Feyz", "Firouzeh", "Firuz", "Firuzeh", "Ghasem",
    "Gholam", "Gholamreza", "Ghoncheh", "Ghorban", "Gol", "Golbahar",
    "Golshah", "Golshan", "Golzar", "Habib", "Hadi", "Hajar", "Hamed",
    "Hamid", "Hamide", "Hamideh", "Hanieh", "Hasan", "Hashem",
    "Hassan", "Hayat", "Hedieh", "Heydar", "Hoda", "Hojjat", "Hossein",
    "Iman", "Isa", "Jafar", "Jahan", "Jahanara", "Jahangir", "Jalal",
    "Jaleh", "Jalil", "Jamaluddin", "Jamileh", "Jamsheed", "Javad",
    "Javed", "Kamal", "Karim", "Katayun", "Kazem", "Khadijeh", "Khalil",
    "Khodadad", "Khorshid", "Kian", "Kianoush", "Kurosh", "Leila",
    "Leili", "Leyla", "Leyli", "Mahboubeh", "Mahdi", "Mahin", "Mahine",
    "Mahmoud", "Mahmud", "Mahvash", "Majid", "Malek", "Maliheh",
    "Mansour", "Mansoureh", "Maryam", "Marzieh", "Masood", "Masoomeh",
    "Masoud", "Masoumeh", "Massoud", "Masud", "Matin", "Mehdi", "Mehr",
    "Mehri", "Meysam", "Mina", "Minu", "Mirza", "Mohammad",
    "Mohammad-Ali", "Mohammad-Reza", "Mohsen", "Mojdeh", "Mojtaba",
    "Mokhtar", "Morad", "Morteza", "Morvarid", "Moslem", "Mostafa",
    "Mousa", "Mozaffar", "Mozhdeh", "Mozhgan", "Nader", "Naheed",
    "Najmeh", "Naser", "Nasir", "Nasrin", "Nasser", "Naveed", "Nazli",
    "Nematollah", "Niousha", "Niusha", "Noor-Ali", "Noureddin",
    "Nousha", "Paniz", "Parastu", "Parvaneh", "Parvin", "Parwiz",
    "Pirouz", "Piruz", "Pouran", "Qasem", "Raheleh", "Rahim", "Rahman",
    "Rahmat", "Rahmatollah", "Rasoul", "Razieh", "Reyhaneh", "Reza",
    "Robab", "Robabeh", "Roghayeh", "Roozbeh", "Roshan", "Roshanara",
    "Rouzbeh", "Saam", "Saber", "Sadaf", "Sadegh", "Sadeq", "Saeed",
    "Saeid", "Safa", "Sajjad", "Sakineh", "Salman", "Samaneh",
    "Samira", "Sardar", "Sedigheh", "Setare", "Seyed", "Seyyed",
    "Shad", "Shadi", "Shaheen", "Shahla", "Shahnaz", "Shahrazad",
    "Shahrbanoo", "Shahriyar", "Shahrzad", "Shahzad", "Shams",
    "Shapur", "Sharif", "Shereen", "Shir", "Shireen", "Shohre",
    "Shokoufeh", "Shokufeh", "Shukria", "Siamak", "Siavush", "Sima",
    "Sina", "Soheila", "Soleiman", "Somayeh", "Soodeh", "Soudeh",
    "Taher", "Tahereh", "Tahmasb", "Tahmasp", "Tayebeh", "Vahid",
    "Yahya", "Yasamin", "Yaser", "Yasin", "Yasser", "Yazdan", "Younes",
    "Yousef", "Yusef", "Zafar", "Zahir", "Zahra", "Zartosht", "Zeinab",
    "Zeynab", "Zhubin", "Ziaeddin", "Zinat",
]

IRANIAN_FIRST_NAMES = sorted(dict.fromkeys(IRANIAN_FIRST_NAMES), key=str.lower)


# Common Iranian/Persian surnames for prospect discovery by family name.
# Mix of distinctly-Persian (city/heritage based) and high-frequency surnames;
# the iranian_score still filters non-Iranian hits.
IRANIAN_SURNAMES = [
    "Mohammadi", "Hosseini", "Ahmadi", "Karimi", "Rahimi", "Moradi",
    "Rezaei", "Hashemi", "Jafari", "Kazemi", "Mousavi", "Bagheri",
    "Tehrani", "Esfahani", "Shirazi", "Tabrizi", "Azizi", "Rostami",
    "Sadeghi", "Akbari", "Soltani", "Naderi", "Heydari", "Nazari",
    "Yousefi", "Amini", "Ebrahimi", "Asadi", "Ghorbani", "Abbasi",
    "Salehi", "Mahmoudi", "Taheri", "Zarei", "Najafi", "Alavi",
    "Ansari", "Bahrami", "Ghasemi", "Habibi", "Jalali", "Kamali",
    "Mirzaei", "Rashidi", "Sharifi", "Vahidi", "Zamani", "Nouri",
    "Kiani", "Daneshvar",
]

IRANIAN_SURNAMES = sorted(dict.fromkeys(IRANIAN_SURNAMES), key=str.lower)
